#!/bin/bash

#SBATCH -p gpu20
##SBATCH --ntasks=16
#SBATCH --nodes=1
##SBATCH --mem=200000
#SBATCH --gres gpu:1
#SBATCH -t 0-11:59:59
#SBATCH -o out_primal/slurm/%j.out
####SBATCH --signal=SIGUSR1@90

# Make conda available:
. ~/.bashrc_private
eval "$(conda shell.bash hook)"
# Activate a conda environment:
conda activate LearnDBCA

FEATURE_EXTRACTOR_DEPTH=1
PRIMAL_PRED_DEPTH=5
VAR_FEATURE_DIM=16
CON_FEATURE_DIM=64
EDGE_FEATURE_DIM=16
NUM_DUAL_ITR=500
GRAD_DUAL_ITR_MAX_ITR=50
USE_LAYER_NORM=True
LR=1e-3
PREDICT_DIST_WEIGHTS=False
LOSS_MARGIN=0.0
NUM_ROUNDS_WITH_GRAD=1
MIN_PERTURBATION=1e-4
MAX_NUM_ROUNDS=3
python train_primal_rounding.py --config-file config_primal/config_worms.py \
    MODEL.FEATURE_EXTRACTOR_DEPTH ${FEATURE_EXTRACTOR_DEPTH} \
    MODEL.PRIMAL_PRED_DEPTH ${PRIMAL_PRED_DEPTH} \
    MODEL.VAR_FEATURE_DIM ${VAR_FEATURE_DIM} \
    MODEL.CON_FEATURE_DIM ${CON_FEATURE_DIM} \
    MODEL.EDGE_FEATURE_DIM ${EDGE_FEATURE_DIM} \
    MODEL.USE_LAYER_NORM ${USE_LAYER_NORM} \
    TRAIN.NUM_ROUNDS ${MAX_NUM_ROUNDS} \
    TRAIN.LOSS_MARGIN ${LOSS_MARGIN} \
    TRAIN.NUM_DUAL_ITERATIONS ${NUM_DUAL_ITR} \
    TRAIN.GRAD_DUAL_ITR_MAX_ITR ${GRAD_DUAL_ITR_MAX_ITR} \
    TRAIN.BASE_LR ${LR} \
    MODEL.PREDICT_DIST_WEIGHTS ${PREDICT_DIST_WEIGHTS} \
    TRAIN.NUM_ROUNDS_WITH_GRAD ${NUM_ROUNDS_WITH_GRAD} \
    TRAIN.MIN_PERTURBATION ${MIN_PERTURBATION} \
    OUT_REL_DIR WORMS/lb_loss_v4/v1_cache_${FEATURE_EXTRACTOR_DEPTH}_${PRIMAL_PRED_DEPTH}_${VAR_FEATURE_DIM}_${CON_FEATURE_DIM}_${EDGE_FEATURE_DIM}_${NUM_DUAL_ITR}_${GRAD_DUAL_ITR_MAX_ITR}_${USE_LAYER_NORM}_${LR}_${PREDICT_DIST_WEIGHTS}_${LOSS_MARGIN}_${NUM_ROUNDS_WITH_GRAD}_${MIN_PERTURBATION}_${MAX_NUM_ROUNDS}

exit 0