#!/bin/bash

#SBATCH -p recon
#SBATCH --ntasks=16
#SBATCH --nodes=1
#SBATCH --mem=200000
#SBATCH --gres gpu:1
#SBATCH -t 0-23:59:59
#SBATCH -o out_primal/slurm/%j.out
####SBATCH --signal=SIGUSR1@90

# Make conda available:
. ~/.bashrc_private
eval "$(conda shell.bash hook)"
# Activate a conda environment:
conda activate LearnDBCA

FEATURE_EXTRACTOR_DEPTH=1
PRIMAL_PRED_DEPTH=3
VAR_FEATURE_DIM=16
CON_FEATURE_DIM=32
EDGE_FEATURE_DIM=16
NUM_DUAL_ITR=20
GRAD_DUAL_ITR_MAX_ITR=10
USE_LAYER_NORM=True
LR=1e-3
PREDICT_DIST_WEIGHTS=False
LOSS_MARGIN=1e-5

python train_primal_rounding.py --config-file config_primal/config_worms.py \
    MODEL.FEATURE_EXTRACTOR_DEPTH ${FEATURE_EXTRACTOR_DEPTH} \
    MODEL.PRIMAL_PRED_DEPTH ${PRIMAL_PRED_DEPTH} \
    MODEL.VAR_FEATURE_DIM ${VAR_FEATURE_DIM} \
    MODEL.CON_FEATURE_DIM ${CON_FEATURE_DIM} \
    MODEL.EDGE_FEATURE_DIM ${EDGE_FEATURE_DIM} \
    MODEL.USE_LAYER_NORM ${USE_LAYER_NORM} \
    TRAIN.LOSS_MARGIN ${LOSS_MARGIN} \
    TRAIN.NUM_DUAL_ITERATIONS ${NUM_DUAL_ITR} \
    TRAIN.GRAD_DUAL_ITR_MAX_ITR ${GRAD_DUAL_ITR_MAX_ITR} \
    TRAIN.BASE_LR ${LR} \
    MODEL.PREDICT_DIST_WEIGHTS ${PREDICT_DIST_WEIGHTS} \
    OUT_REL_DIR WORMS/v1_var_pert_${FEATURE_EXTRACTOR_DEPTH}_${PRIMAL_PRED_DEPTH}_${VAR_FEATURE_DIM}_${CON_FEATURE_DIM}_${EDGE_FEATURE_DIM}_${NUM_DUAL_ITR}_${GRAD_DUAL_ITR_MAX_ITR}_${USE_LAYER_NORM}_${LR}_${PREDICT_DIST_WEIGHTS}_${LOSS_MARGIN}

exit 0