#!/bin/bash

#SBATCH -p gpu20
##SBATCH --ntasks=16
#SBATCH --nodes=1
##SBATCH --mem=200000
#SBATCH --gres gpu:1
#SBATCH -t 1-23:59:59
#SBATCH -o out_primal/slurm/%j_worms.out
####SBATCH --signal=SIGUSR1@90

# Make conda available:
. ~/.bashrc_private
eval "$(conda shell.bash hook)"
# Activate a conda environment:
conda activate LearnDBCA

FEATURE_EXTRACTOR_DEPTH=1
PRIMAL_PRED_DEPTH=1
VAR_FEATURE_DIM=32
CON_FEATURE_DIM=32
EDGE_FEATURE_DIM=16
NUM_DUAL_ITR=500
GRAD_DUAL_ITR_MAX_ITR=50
USE_LAYER_NORM=True
LR=1e-3
LOSS_MARGIN=0.0
NUM_ROUNDS_WITH_GRAD=7
MIN_PERTURBATION=1e-4
MAX_NUM_ROUNDS=20
USE_LSTM=True
FOLDER_NAME=v1_with_round_index_${FEATURE_EXTRACTOR_DEPTH}_${PRIMAL_PRED_DEPTH}_${VAR_FEATURE_DIM}_${CON_FEATURE_DIM}_${EDGE_FEATURE_DIM}_${NUM_DUAL_ITR}_${GRAD_DUAL_ITR_MAX_ITR}_${USE_LAYER_NORM}_${LR}_${LOSS_MARGIN}_${NUM_ROUNDS_WITH_GRAD}_${MIN_PERTURBATION}_${MAX_NUM_ROUNDS}_${USE_LSTM}

echo ${FOLDER_NAME}
python train_primal_rounding.py --test-non-learned --config-file config_primal/config_worms.py \
    MODEL.FEATURE_EXTRACTOR_DEPTH ${FEATURE_EXTRACTOR_DEPTH} \
    MODEL.PRIMAL_PRED_DEPTH ${PRIMAL_PRED_DEPTH} \
    MODEL.VAR_FEATURE_DIM ${VAR_FEATURE_DIM} \
    MODEL.CON_FEATURE_DIM ${CON_FEATURE_DIM} \
    MODEL.EDGE_FEATURE_DIM ${EDGE_FEATURE_DIM} \
    MODEL.USE_LAYER_NORM ${USE_LAYER_NORM} \
    MODEL.USE_LSTM_VAR ${USE_LSTM} \
    TRAIN.NUM_ROUNDS ${MAX_NUM_ROUNDS} \
    TRAIN.LOSS_MARGIN ${LOSS_MARGIN} \
    TRAIN.NUM_DUAL_ITERATIONS ${NUM_DUAL_ITR} \
    TRAIN.GRAD_DUAL_ITR_MAX_ITR ${GRAD_DUAL_ITR_MAX_ITR} \
    TRAIN.BASE_LR ${LR} \
    TRAIN.NUM_ROUNDS_WITH_GRAD ${NUM_ROUNDS_WITH_GRAD} \
    TRAIN.MIN_PERTURBATION ${MIN_PERTURBATION} \
    OUT_REL_DIR WORMS/v2/${FOLDER_NAME}

exit 0