#!/bin/bash

#SBATCH -p gpu20
##SBATCH -w recon02
##SBATCH --ntasks=16
#SBATCH --nodes=1
##SBATCH --mem=250000
#SBATCH --gres gpu:1
#SBATCH -t 0-23:59:59
#SBATCH -o out_dual/slurm_new/%j.out
####SBATCH --signal=SIGUSR1@90

# Make conda available:
. ~/.bashrc_private
eval "$(conda shell.bash hook)"
# Activate a conda environment:
conda activate LearnDBCA

#export GRB_LICENSE_FILE=/home/ahabbas/gurobi_recon02/gurobi.lic
FEATURE_EXTRACTOR_DEPTH=1
DUAL_PRED_DEPTH=1
VAR_FEATURE_DIM=16
CON_FEATURE_DIM=16
EDGE_FEATURE_DIM=8
NUM_ROUNDS_WITH_GRAD=1
NUM_DUAL_ITR=5
GRAD_DUAL_ITR_MAX_ITR=5
NUM_ROUNDS_TRAIN=100
BASE_LR=1e-3
NUM_HIDDEN_LAYERS_EDGE=2
USE_RELATIVE_GAP_LOSS=False
USE_NET_SOLVER_COSTS=True
USE_LSTM_VAR=False
FREE_UPDATE=True
NUM_JOURNEYS=10
PREDICT_OMEGA=False
PREDICT_DIST_WEIGHTS=False
FREE_UPDATE_LOSS_WEIGHT=1.0
DENORM_FREE_UPDATE=False

# \
python train_dual_ascent.py --config-file config_dual/config_spp_full.py \
    OUT_REL_DIR SPP/nobackup/v4_mixed_${FEATURE_EXTRACTOR_DEPTH}_${DUAL_PRED_DEPTH}_${VAR_FEATURE_DIM}_${CON_FEATURE_DIM}_${EDGE_FEATURE_DIM}_${NUM_ROUNDS_WITH_GRAD}_${NUM_DUAL_ITR}_${GRAD_DUAL_ITR_MAX_ITR}_${NUM_ROUNDS_TRAIN}_${PREDICT_OMEGA}_${PREDICT_DIST_WEIGHTS}_${BASE_LR}_${USE_RELATIVE_GAP_LOSS}_${NUM_HIDDEN_LAYERS_EDGE}_${USE_NET_SOLVER_COSTS}_${USE_LSTM_VAR}_${FREE_UPDATE}_${NUM_JOURNEYS}_${FREE_UPDATE_LOSS_WEIGHT}_${DENORM_FREE_UPDATE} \
    MODEL.FEATURE_EXTRACTOR_DEPTH ${FEATURE_EXTRACTOR_DEPTH} \
    TRAIN.BASE_LR ${BASE_LR} \
    TRAIN.USE_RELATIVE_GAP_LOSS ${USE_RELATIVE_GAP_LOSS} \
    MODEL.DUAL_PRED_DEPTH ${DUAL_PRED_DEPTH} \
    MODEL.VAR_FEATURE_DIM ${VAR_FEATURE_DIM} \
    MODEL.CON_FEATURE_DIM ${CON_FEATURE_DIM} \
    MODEL.EDGE_FEATURE_DIM ${EDGE_FEATURE_DIM} \
    MODEL.NUM_HIDDEN_LAYERS_EDGE ${NUM_HIDDEN_LAYERS_EDGE} \
    TRAIN.NUM_ROUNDS_WITH_GRAD ${NUM_ROUNDS_WITH_GRAD} \
    TRAIN.NUM_DUAL_ITERATIONS ${NUM_DUAL_ITR} \
    TRAIN.GRAD_DUAL_ITR_MAX_ITR ${GRAD_DUAL_ITR_MAX_ITR} \
    MODEL.PREDICT_OMEGA ${PREDICT_OMEGA} \
    MODEL.PREDICT_DIST_WEIGHTS ${PREDICT_DIST_WEIGHTS} \
    TRAIN.NUM_ROUNDS ${NUM_ROUNDS_TRAIN} \
    MODEL.USE_NET_SOLVER_COSTS ${USE_NET_SOLVER_COSTS} \
    MODEL.USE_LSTM_VAR ${USE_LSTM_VAR} \
    MODEL.FREE_UPDATE ${FREE_UPDATE} \
    TRAIN.NUM_JOURNEYS ${NUM_JOURNEYS} \
    TRAIN.FREE_UPDATE_LOSS_WEIGHT ${FREE_UPDATE_LOSS_WEIGHT} \
    MODEL.DENORM_FREE_UPDATE ${DENORM_FREE_UPDATE}

exit 0