#!/bin/bash

#SBATCH -p gpu20
#SBATCH --ntasks=16
#SBATCH --nodes=1
#SBATCH --mem=200000
#SBATCH --gres gpu:1
#SBATCH -t 1-23:59:59
#SBATCH -o out_dual/slurm/%j.out
####SBATCH --signal=SIGUSR1@90

# Make conda available:
. ~/.bashrc_private
eval "$(conda shell.bash hook)"
# Activate a conda environment:
conda activate LearnDBCA

FEATURE_EXTRACTOR_DEPTH=1
DUAL_PRED_DEPTH=5
VAR_FEATURE_DIM=16
CON_FEATURE_DIM=64
EDGE_FEATURE_DIM=16
NUM_ROUNDS_WITH_GRAD=1
NUM_DUAL_ITR=1 # compare with 1_1_100 as it computes mm diff.
GRAD_DUAL_ITR_MAX_ITR=1
PREDICT_OMEGA=True
SKIP_CONNECTIONS=False
NUM_ROUNDS_TRAIN=1000
#--test-non-learned \
python train_dual_ascent.py --config-file config_dual/config_worms_full_coord.py \
    OUT_REL_DIR WORMS_FULL_COORD/v3_${FEATURE_EXTRACTOR_DEPTH}_${DUAL_PRED_DEPTH}_${VAR_FEATURE_DIM}_${CON_FEATURE_DIM}_${EDGE_FEATURE_DIM}_${NUM_ROUNDS_WITH_GRAD}_${NUM_DUAL_ITR}_${GRAD_DUAL_ITR_MAX_ITR}_${SKIP_CONNECTIONS}_${NUM_ROUNDS_TRAIN}_${PREDICT_OMEGA} \
    MODEL.FEATURE_EXTRACTOR_DEPTH ${FEATURE_EXTRACTOR_DEPTH} \
    MODEL.SKIP_CONNECTIONS ${SKIP_CONNECTIONS} \
    MODEL.DUAL_PRED_DEPTH ${DUAL_PRED_DEPTH} \
    MODEL.VAR_FEATURE_DIM ${VAR_FEATURE_DIM} \
    MODEL.CON_FEATURE_DIM ${CON_FEATURE_DIM} \
    MODEL.EDGE_FEATURE_DIM ${EDGE_FEATURE_DIM} \
    TRAIN.NUM_ROUNDS_WITH_GRAD ${NUM_ROUNDS_WITH_GRAD} \
    TRAIN.NUM_DUAL_ITERATIONS ${NUM_DUAL_ITR} \
    TRAIN.GRAD_DUAL_ITR_MAX_ITR ${GRAD_DUAL_ITR_MAX_ITR} \
    MODEL.PREDICT_OMEGA ${PREDICT_OMEGA} \
    TRAIN.NUM_ROUNDS ${NUM_ROUNDS_TRAIN}

exit 0