#!/bin/bash

#SBATCH -p gpu20
##SBATCH -w gpu22-a100-01
##SBATCH --ntasks=16
##SBATCH --nodes=1
##SBATCH --mem=255000
#SBATCH --gres gpu:1
#SBATCH -t 1-23:59:59
#SBATCH -o out_dual/slurm_new/%j.out
#SBATCH --mail-type=end          # send email when job ends
#SBATCH --mail-user=ahmed.abbas@mpi-inf.mpg.de
####SBATCH --signal=SIGUSR1@90

# Make conda available:
. ~/.bashrc
eval "$(conda shell.bash hook)"
# Activate a conda environment:
conda activate LearnDBCA_new_old_glib

export GRB_LICENSE_FILE=/home/ahabbas/gurobi_gpu22_a100_a01/gurobi.lic

FEATURE_EXTRACTOR_DEPTH=1
DUAL_PRED_DEPTH=1
VAR_FEATURE_DIM=16
CON_FEATURE_DIM=16
EDGE_FEATURE_DIM=8
NUM_ROUNDS_WITH_GRAD=1
NUM_DUAL_ITR=5
GRAD_DUAL_ITR_MAX_ITR=5
PREDICT_OMEGA=True
PREDICT_DIST_WEIGHTS=True
NUM_ROUNDS_TRAIN=50
BASE_LR=1e-2
NUM_HIDDEN_LAYERS_EDGE=2
USE_RELATIVE_GAP_LOSS=False
USE_NET_SOLVER_COSTS=True
FREE_UPDATE=True
FREE_UPDATE_LOSS_WEIGHT=0.0
DENORM_FREE_UPDATE=False
USE_CELU_ACTIVATION=False
USE_SEPARATE_MODEL_LATER_STAGE=True

# --test-non-learned --train-precision-double
python train_dual_ascent.py --config-file config_dual/config_shape_matching.py --test-precision-float \
    OUT_REL_DIR SM/nobackup/vf/v6_new_split_mean_agg_clip_bs_2_200_ep_${FEATURE_EXTRACTOR_DEPTH}_${DUAL_PRED_DEPTH}_${VAR_FEATURE_DIM}_${CON_FEATURE_DIM}_${EDGE_FEATURE_DIM}_${NUM_ROUNDS_WITH_GRAD}_${NUM_DUAL_ITR}_${GRAD_DUAL_ITR_MAX_ITR}_${NUM_ROUNDS_TRAIN}_${PREDICT_OMEGA}_${PREDICT_DIST_WEIGHTS}_${BASE_LR}_${USE_RELATIVE_GAP_LOSS}_${NUM_HIDDEN_LAYERS_EDGE}_${USE_NET_SOLVER_COSTS}_${FREE_UPDATE}_${FREE_UPDATE_LOSS_WEIGHT}_${DENORM_FREE_UPDATE} \
    MODEL.FEATURE_EXTRACTOR_DEPTH ${FEATURE_EXTRACTOR_DEPTH} \
    TRAIN.BASE_LR ${BASE_LR} \
    TRAIN.USE_RELATIVE_GAP_LOSS ${USE_RELATIVE_GAP_LOSS} \
    MODEL.DUAL_PRED_DEPTH ${DUAL_PRED_DEPTH} \
    MODEL.VAR_FEATURE_DIM ${VAR_FEATURE_DIM} \
    MODEL.CON_FEATURE_DIM ${CON_FEATURE_DIM} \
    MODEL.EDGE_FEATURE_DIM ${EDGE_FEATURE_DIM} \
    MODEL.NUM_HIDDEN_LAYERS_EDGE ${NUM_HIDDEN_LAYERS_EDGE} \
    TRAIN.NUM_ROUNDS_WITH_GRAD ${NUM_ROUNDS_WITH_GRAD} \
    TRAIN.NUM_DUAL_ITERATIONS ${NUM_DUAL_ITR} \
    TRAIN.GRAD_DUAL_ITR_MAX_ITR ${GRAD_DUAL_ITR_MAX_ITR} \
    MODEL.PREDICT_OMEGA ${PREDICT_OMEGA} \
    MODEL.PREDICT_DIST_WEIGHTS ${PREDICT_DIST_WEIGHTS} \
    TRAIN.NUM_ROUNDS ${NUM_ROUNDS_TRAIN} \
    MODEL.USE_NET_SOLVER_COSTS ${USE_NET_SOLVER_COSTS} \
    MODEL.FREE_UPDATE ${FREE_UPDATE} \
    TRAIN.FREE_UPDATE_LOSS_WEIGHT ${FREE_UPDATE_LOSS_WEIGHT} \
    MODEL.DENORM_FREE_UPDATE ${DENORM_FREE_UPDATE} \
    MODEL.USE_SEPARATE_MODEL_LATER_STAGE ${USE_SEPARATE_MODEL_LATER_STAGE} \
    TRAIN.GRAD_CLIP_VAL 50.0 \
    TRAIN.BATCH_SIZE 2

exit 0